decompiler: PcodeOpRaw Class Reference
PcodeOpRaw Class Reference
A low-level representation of a single pcode operation.
#include <pcoderaw.hh>
Public Member Functions
void setBehavior (OpBehavior *be)
Set the opcode for this op.
OpBehavior * getBehavior (void) const
Retrieve the behavior for this op.
OpCode getOpcode (void) const
Get the opcode for this op.
void setSeqNum (const Address &a, uintm b)
Set the sequence number.
const SeqNum & getSeqNum (void) const
Retrieve the sequence number.
const Address & getAddr (void) const
Get address of this operation.
void setOutput (VarnodeData *o)
Set the output varnode for this op.
VarnodeData * getOutput (void) const
Retrieve the output varnode for this op.
void addInput (VarnodeData *i)
Add an additional input varnode to this op.
void clearInputs (void)
Remove all input varnodes to this op.
int4 numInput (void) const
Get the number of input varnodes to this op.
VarnodeData * getInput (int4 i) const
Get the i-th input varnode for this op.
Private Attributes
OpBehavior * behave
The opcode for this operation.
SeqNum seq
Identifying address and index of this operation.
VarnodeData * out
Output varnode triple.
vector< VarnodeData * > in
Raw varnode inputs to this op.
Detailed Description
A low-level representation of a single pcode operation.
This is just the minimum amount of data to represent a pcode operation An opcode, sequence number, optional output varnode and input varnodes
Member Function Documentation
addInput()
void PcodeOpRaw::addInput (VarnodeData * i) inline
Add an additional input varnode to this op.
A PcodeOpRaw is initially created with no input varnodes. Inputs are added with this method. Varnodes are added in order, so the first addInput call creates input 0, for example.
Parameters
i is the varnode to be added as input
Referenced by PcodeEmitCache::dump().
clearInputs()
void PcodeOpRaw::clearInputs (void) inline
Remove all input varnodes to this op.
If the inputs to a pcode operation need to be changed, this routine clears the existing inputs so new ones can be added.
getAddr()
const Address & PcodeOpRaw::getAddr (void) const inline
Get address of this operation.
This is a convenience function to get the address of the machine instruction (of which this pcode op is a translation)
Returns
the machine instruction address
getBehavior()
OpBehavior * PcodeOpRaw::getBehavior (void) const inline
Retrieve the behavior for this op.
Get the underlying behavior object for this pcode operation. From this object you can determine how the object evaluates inputs to get the output
Returns
the behavior object
Referenced by EmulatePcodeCache::establishOp().
getInput()
VarnodeData * PcodeOpRaw::getInput (int4 i) const inline
Get the i-th input varnode for this op.
Input varnodes are indexed starting at 0. This retrieves the input varnode by index. The index must be in range, or unpredicatable behavior will result. Use the numInput method to get the number of inputs.
Parameters
i is the index of the desired input
Returns
the desired input varnode
Referenced by BreakTableCallBack::doPcodeOpBreak(), and EmulatePcodeCache::executeBranch().
getOpcode()
OpCode PcodeOpRaw::getOpcode (void) const inline
Get the opcode for this op.
The possible types of pcode operations are enumerated by OpCode This routine retrieves the enumeration value for this particular op
Returns
the opcode value
getOutput()
VarnodeData * PcodeOpRaw::getOutput (void) const inline
Retrieve the output varnode for this op.
Most pcode operations have an output varnode. This routine retrieves that varnode.
Returns
the output varnode or null if there is no output
getSeqNum()
const SeqNum & PcodeOpRaw::getSeqNum (void) const inline
Retrieve the sequence number.
Every pcode operation has a sequence number which associates the operation with the address of the machine instruction being translated and an index number for this operation within the translation.
Returns
a reference to the sequence number
numInput()
int4 PcodeOpRaw::numInput (void) const inline
Get the number of input varnodes to this op.
Returns
the number of inputs
setBehavior()
void PcodeOpRaw::setBehavior (OpBehavior * be) inline
Set the opcode for this op.
The core behavior for this operation is controlled by an OpBehavior object which knows how output is determined given inputs. This routine sets that object
Parameters
be is the behavior object
Referenced by PcodeEmitCache::dump().
setOutput()
void PcodeOpRaw::setOutput (VarnodeData * o) inline
Set the output varnode for this op.
Most pcode operations output to a varnode. This routine sets what that varnode is.
Parameters
o is the varnode to set as output
Referenced by PcodeEmitCache::dump().
setSeqNum()
void PcodeOpRaw::setSeqNum (const Address & a, uintm b) inline
Set the sequence number.
Every pcode operation has a sequence number which associates the operation with the address of the machine instruction being translated and an order number which provides an index for this particular operation within the entire translation of the machine instruction
Parameters
a is the instruction address
b is the order number
Referenced by PcodeEmitCache::dump().
The documentation for this class was generated from the following file:
pcoderaw.hh