decompiler: TrackedContext Struct Reference
TrackedContext Struct Reference
A tracked register (Varnode) and the value it contains.
#include <globalcontext.hh>
Public Member Functions
void restoreXml (const Element *el, const AddrSpaceManager *manage)
Restore this from an XML stream.
void saveXml (ostream &s) const
Save this to an XML stream.
Public Attributes
VarnodeData loc
Storage details of the register being tracked.
uintb val
The value of the register.
Detailed Description
A tracked register (Varnode) and the value it contains.
This is the object returned when querying for tracked registers, via ContextDatabase::getTrackedSet(). It holds the storage details of the register and the actual value it holds at the point of the query.
Member Function Documentation
restoreXml()
void TrackedContext::restoreXml (const Element * el, const AddrSpaceManager * manage)
Restore this from an XML stream.
Read a <set> tag to fill in the storage and value details
Parameters
el is the root <set> tag
manage is the manager used to decode address references
References Address::getOffset(), Address::getSpace(), and Address::restoreXml().
saveXml()
void TrackedContext::saveXml (ostream & s) const
Save this to an XML stream.
The register storage and value are serialized as a <set> tag.
Parameters
s is the output stream
The documentation for this struct was generated from the following files:
globalcontext.hh
globalcontext.cc