decompiler: BreakTableCallBack Class Reference
BreakTableCallBack Class Reference
A basic instantiation of a breakpoint table.
#include <emulate.hh>
Public Member Functions
BreakTableCallBack (Translate *t)
Basic breaktable constructor.
void registerPcodeCallback (const string &nm, BreakCallBack *func)
Register a pcode based breakpoint.
void registerAddressCallback (const Address &addr, BreakCallBack *func)
Register an address based breakpoint.
virtual void setEmulate (Emulate *emu)
Associate an emulator with all breakpoints in the table.
virtual bool doPcodeOpBreak (PcodeOpRaw *curop)
Invoke any breakpoints for the given pcode op.
virtual bool doAddressBreak (const Address &addr)
Invoke any breakpoints for the given address.
Private Attributes
Emulate * emulate
The emulator associated with this table.
Translate * trans
The translator.
map< Address, BreakCallBack * > addresscallback
a container of pcode based breakpoints
map< uintb, BreakCallBack * > pcodecallback
a container of addressed based breakpoints
Detailed Description
A basic instantiation of a breakpoint table.
This object allows breakpoints to registered in the table via either
registerPcodeCallback() or = registerAddressCallback()
Breakpoints are stored in map containers, and the core BreakTable methods are implemented to search in these containers
Constructor & Destructor Documentation
BreakTableCallBack()
BreakTableCallBack::BreakTableCallBack (Translate * t) inline
Basic breaktable constructor.
The break table needs a translator object so user-defined pcode ops can be registered against by name.
Parameters
t is the translator object
Member Function Documentation
doAddressBreak()
bool BreakTableCallBack::doAddressBreak (const Address & addr) virtual
Invoke any breakpoints for the given address.
This routine examines the address based container for any breakpoints associated with the given address. If one is found, its addressCallback method is invoked.
Parameters
addr is the address being checked for breakpoints
Returns
true if the breakpoint exists and returns true, otherwise return false
Implements BreakTable.
References addresscallback.
doPcodeOpBreak()
bool BreakTableCallBack::doPcodeOpBreak (PcodeOpRaw * curop) virtual
Invoke any breakpoints for the given pcode op.
This routine examines the pcode-op based container for any breakpoints associated with the given op. If one is found, its pcodeCallback method is invoked.
Parameters
curop is pcode op being checked for breakpoints
Returns
true if the breakpoint exists and returns true, otherwise return false
Implements BreakTable.
References PcodeOpRaw::getInput(), VarnodeData::offset, and pcodecallback.
registerAddressCallback()
void BreakTableCallBack::registerAddressCallback (const Address & addr, BreakCallBack * func)
Register an address based breakpoint.
Any time the emulator is about to execute (the pcode translation of) a particular machine instruction at this address, the indicated breakpoint is invoked first. The break table does not assume responsibility for freeing the breakpoint object.
Parameters
addr is the address associated with the breakpoint
func is the breakpoint being registered
References addresscallback, emulate, and BreakCallBack::setEmulate().
registerPcodeCallback()
void BreakTableCallBack::registerPcodeCallback (const string & name, BreakCallBack * func)
Register a pcode based breakpoint.
Any time the emulator is about to execute a user-defined pcode op with the given name, the indicated breakpoint is invoked first. The break table does not assume responsibility for freeing the breakpoint object.
Parameters
name is the name of the user-defined pcode op
func is the breakpoint object to associate with the pcode op
References emulate, Translate::getUserOpNames(), pcodecallback, BreakCallBack::setEmulate(), and trans.
setEmulate()
void BreakTableCallBack::setEmulate (Emulate * emu) virtual
Associate an emulator with all breakpoints in the table.
This routine invokes the setEmulate method on each breakpoint currently in the table
Parameters
emu is the emulator to be associated with the breakpoints
Implements BreakTable.
References addresscallback, emulate, and pcodecallback.
The documentation for this class was generated from the following files:
emulate.hh
emulate.cc