decompiler: MemoryPageOverlay Class Reference
MemoryPageOverlay Class Reference
Memory bank that overlays some other memory bank, using a "copy on write" behavior.
#include <memstate.hh>
Public Member Functions
MemoryPageOverlay (AddrSpace *spc, int4 ws, int4 ps, MemoryBank *ul)
Constructor for page overlay.
Public Member Functions inherited from MemoryBank
MemoryBank (AddrSpace *spc, int4 ws, int4 ps)
Generic constructor for a memory bank.
int4 getWordSize (void) const
Get the number of bytes in a word for this memory bank.
int4 getPageSize (void) const
Get the number of bytes in a page for this memory bank.
AddrSpace * getSpace (void) const
Get the address space associated with this memory bank.
void setValue (uintb offset, int4 size, uintb val)
Set the value of a (small) range of bytes.
uintb getValue (uintb offset, int4 size) const
Retrieve the value encoded in a (small) range of bytes.
void setChunk (uintb offset, int4 size, const uint1 *val)
Set values of an arbitrary sequence of bytes.
void getChunk (uintb offset, int4 size, uint1 *res) const
Retrieve an arbitrary sequence of bytes.
Protected Member Functions
virtual void insert (uintb addr, uintb val)
Overridden aligned word insert.
virtual uintb find (uintb addr) const
Overridden aligned word find.
virtual void getPage (uintb addr, uint1 *res, int4 skip, int4 size) const
Overridden getPage.
virtual void setPage (uintb addr, const uint1 *val, int4 skip, int4 size)
Overridden setPage.
Private Attributes
MemoryBank * underlie
Underlying memory object.
map< uintb, uint1 * > page
Overlayed pages.
Additional Inherited Members
Static Public Member Functions inherited from MemoryBank
static uintb constructValue (const uint1 *ptr, int4 size, bool bigendian)
Decode bytes to value.
static void deconstructValue (uint1 *ptr, uintb val, int4 size, bool bigendian)
Encode value to bytes.
Detailed Description
Memory bank that overlays some other memory bank, using a "copy on write" behavior.
Pages are copied from the underlying object only when there is a write. The underlying access routines are overridden to make optimal use of this page implementation. The underlying memory bank can be a null pointer in which case, this memory bank behaves as if it were initially filled with zeros.
Constructor & Destructor Documentation
MemoryPageOverlay()
MemoryPageOverlay::MemoryPageOverlay (AddrSpace * spc, int4 ws, int4 ps, MemoryBank * ul)
Constructor for page overlay.
A page overlay memory bank needs all the parameters for a generic memory bank and it needs to know the underlying memory bank being overlayed.
Parameters
spc is the address space associated with the memory bank
ws is the number of bytes in the preferred wordsize (must be power of 2)
ps is the number of bytes in a page (must be power of 2)
ul is the underlying MemoryBank
References page, and underlie.
Member Function Documentation
find()
uintb MemoryPageOverlay::find (uintb addr) const protected virtual
Overridden aligned word find.
This derived method first looks for the aligned word in the mapped pages. If the address is not mapped, the search is forwarded to the underlying memory bank. If there is no underlying bank, zero is returned.
Parameters
addr is the aligned offset of the word
Returns
the retrieved value
Implements MemoryBank.
References MemoryBank::constructValue(), MemoryBank::getPageSize(), MemoryBank::getSpace(), and MemoryBank::getWordSize().
getPage()
void MemoryPageOverlay::getPage (uintb addr, uint1 * res, int4 skip, int4 size) const protected virtual
Overridden getPage.
The desired page is looked for in the page cache. If it doesn't exist, the request is forwarded to underlying bank. If there is no underlying bank, the result buffer is filled with zeros.
Parameters
addr is the aligned offset of the page
res is the pointer to where retrieved bytes should be stored
skip is the offset into the page from where bytes should be retrieved
size is the number of bytes to retrieve
Reimplemented from MemoryBank.
insert()
void MemoryPageOverlay::insert (uintb addr, uintb val) protected virtual
Overridden aligned word insert.
This derived method looks for a previously cached page of the underlying memory bank. If the cached page does not exist, it creates it and fills in its initial value by retrieving the page from the underlying bank. The new value is then written into cached page.
Parameters
addr is the aligned address of the word to be written
val is the value to be written at that word
Implements MemoryBank.
References MemoryBank::deconstructValue(), MemoryBank::getPageSize(), MemoryBank::getSpace(), and MemoryBank::getWordSize().
setPage()
void MemoryPageOverlay::setPage (uintb addr, const uint1 * val, int4 skip, int4 size) protected virtual
Overridden setPage.
First, a cached version of the desired page is searched for via its address. If it doesn't exist, it is created, and its initial value is filled via the underlying bank. The bytes to be written are then copied into the cached page.
Parameters
addr is the aligned offset of the page to write
val is a pointer to bytes to be written into the page
skip is the offset into the page where bytes should be written
size is the number of bytes to write
Reimplemented from MemoryBank.
References MemoryBank::getPageSize().
The documentation for this class was generated from the following files:
memstate.hh
memstate.cc