decompiler: FloatFormat Class Reference
FloatFormat Class Reference
Encoding information for a single floating-point format.
#include <float.hh>
Public Types
enum floatclass {
normalized = 0, infinity = 1, zero = 2, nan = 3,
denormalized = 4
}
The various classes of floating-point encodings.
Public Member Functions
FloatFormat (void)
Construct for use with restoreXml()
FloatFormat (int4 sz)
Construct default IEEE 754 standard settings.
int4 getSize (void) const
Get the size of the encoding in bytes.
double getHostFloat (uintb encoding, floatclass *type) const
Convert an encoding into host's double.
uintb getEncoding (double host) const
Convert host's double into this encoding.
uintb convertEncoding (uintb encoding, const FloatFormat *formin) const
Convert between two different formats.
uintb extractFractionalCode (uintb x) const
Extract the fractional part of the encoding.
bool extractSign (uintb x) const
Extract the sign bit from the encoding.
int4 extractExponentCode (uintb x) const
Extract the exponent from the encoding.
uintb opEqual (uintb a, uintb b) const
Equality comparison (==)
uintb opNotEqual (uintb a, uintb b) const
Inequality comparison (!=)
uintb opLess (uintb a, uintb b) const
Less-than comparison (<)
uintb opLessEqual (uintb a, uintb b) const
Less-than-or-equal comparison (<=)
uintb opNan (uintb a) const
Test if Not-a-Number (NaN)
uintb opAdd (uintb a, uintb b) const
Addition (+)
uintb opDiv (uintb a, uintb b) const
Division (/)
uintb opMult (uintb a, uintb b) const
Multiplication (*)
uintb opSub (uintb a, uintb b) const
Subtraction (-)
uintb opNeg (uintb a) const
Unary negate.
uintb opAbs (uintb a) const
Absolute value (abs)
uintb opSqrt (uintb a) const
Square root (sqrt)
uintb opTrunc (uintb a, int4 sizeout) const
Convert floating-point to integer.
uintb opCeil (uintb a) const
Ceiling (ceil)
uintb opFloor (uintb a) const
Floor (floor)
uintb opRound (uintb a) const
Round.
uintb opInt2Float (uintb a, int4 sizein) const
Convert integer to floating-point.
uintb opFloat2Float (uintb a, const FloatFormat &outformat) const
Convert between floating-point precisions.
void saveXml (ostream &s) const
Save the format to an XML stream.
void restoreXml (const Element *el)
Restore the format from XML.
Private Member Functions
uintb setFractionalCode (uintb x, uintb code) const
Set the fractional part of an encoded value.
uintb setSign (uintb x, bool sign) const
Set the sign bit of an encoded value.
uintb setExponentCode (uintb x, uintb code) const
Set the exponent of an encoded value.
uintb getZeroEncoding (bool sgn) const
Get an encoded zero value.
uintb getInfinityEncoding (bool sgn) const
Get an encoded infinite value.
uintb getNaNEncoding (bool sgn) const
Get an encoded NaN value.
Static Private Member Functions
static double createFloat (bool sign, uintb signif, int4 exp)
Create a double given sign, fractional, and exponent.
static floatclass extractExpSig (double x, bool *sgn, uintb *signif, int4 *exp)
Extract the sign, fractional, and exponent from a given floating-point value.
Private Attributes
int4 size
Size of float in bytes (this format)
int4 signbit_pos
Bit position of sign bit.
int4 frac_pos
(lowest) bit position of fractional part
int4 frac_size
Number of bits in fractional part.
int4 exp_pos
(lowest) bit position of exponent
int4 exp_size
Number of bits in exponent.
int4 bias
What to add to real exponent to get encoding.
int4 maxexponent
Maximum possible exponent.
bool jbitimplied
Set to true if integer bit of 1 is assumed.
Detailed Description
Encoding information for a single floating-point format.
This class supports manipulation of a single floating-point encoding. An encoding can be converted to and from the host format and convenience methods allow p-code floating-point operations to be performed on natively encoded operands. This follows the IEEE754 standards.
Member Enumeration Documentation
floatclass
enum FloatFormat::floatclass
The various classes of floating-point encodings.
Enumerator
normalized
A normal floating-point number.
infinity
An encoding representing an infinite value.
zero
An encoding of the value zero.
nan
An invalid encoding, Not-a-Number.
denormalized
A denormalized encoding (for very small values)
Constructor & Destructor Documentation
FloatFormat()
FloatFormat::FloatFormat (int4 sz)
Construct default IEEE 754 standard settings.
Set format for a given encoding size according to IEEE 754 standards
Parameters
sz is the size of the encoding in bytes
References bias, exp_pos, exp_size, frac_pos, frac_size, jbitimplied, maxexponent, signbit_pos, and size.
Member Function Documentation
convertEncoding()
uintb FloatFormat::convertEncoding (uintb encoding, const FloatFormat * formin) const
Convert between two different formats.
Parameters
encoding is the value in the other FloatFormat
formin is the other FloatFormat
Returns
the equivalent value in this FloatFormat
References bias, extractExponentCode(), extractFractionalCode(), extractSign(), getInfinityEncoding(), getZeroEncoding(), jbitimplied, maxexponent, setExponentCode(), setFractionalCode(), and setSign().
Referenced by getSize().
createFloat()
double FloatFormat::createFloat (bool sign, uintb signif, int4 exp) static private
Create a double given sign, fractional, and exponent.
Parameters
sign is set to true if the value should be negative
signif is the fractional part
exp is the exponent
Returns
the constructed floating-point value
Referenced by getHostFloat().
extractExponentCode()
int4 FloatFormat::extractExponentCode (uintb x) const
Extract the exponent from the encoding.
Parameters
x is an encoded floating-point value
Returns
the (signed) exponent
References exp_pos, and exp_size.
Referenced by convertEncoding(), getHostFloat(), and getSize().
extractExpSig()
FloatFormat::floatclass FloatFormat::extractExpSig (double x, bool * sgn, uintb * signif, int4 * exp) static private
Extract the sign, fractional, and exponent from a given floating-point value.
Parameters
x is the given value
sgn passes back the sign
signif passes back the fractional part
exp passes back the exponent
Returns
the floating-point class of the value
References infinity, nan, normalized, and zero.
Referenced by getEncoding().
extractFractionalCode()
uintb FloatFormat::extractFractionalCode (uintb x) const
Extract the fractional part of the encoding.
Parameters
x is an encoded floating-point value
Returns
the fraction part of the value aligned to the top of the word
References frac_pos, and frac_size.
Referenced by convertEncoding(), getHostFloat(), and getSize().
extractSign()
bool FloatFormat::extractSign (uintb x) const
Extract the sign bit from the encoding.
Parameters
x is an encoded floating-point value
Returns
the sign bit
References signbit_pos.
Referenced by convertEncoding(), getHostFloat(), and getSize().
getEncoding()
uintb FloatFormat::getEncoding (double host) const
Convert host's double into this encoding.
Parameters
host is the double value to convert
Returns
the equivalent encoded value
References bias, extractExpSig(), getInfinityEncoding(), getNaNEncoding(), getZeroEncoding(), infinity, jbitimplied, maxexponent, nan, setExponentCode(), setFractionalCode(), setSign(), and zero.
Referenced by getSize(), opAbs(), opAdd(), opCeil(), opDiv(), opFloat2Float(), opFloor(), opInt2Float(), opMult(), opNeg(), opRound(), opSqrt(), and opSub().
getHostFloat()
double FloatFormat::getHostFloat (uintb encoding, floatclass * type) const
Convert an encoding into host's double.
Parameters
encoding is the encoding value
type points to the floating-point class, which is passed back
Returns
the equivalent double value
References bias, createFloat(), denormalized, extractExponentCode(), extractFractionalCode(), extractSign(), infinity, jbitimplied, maxexponent, nan, normalized, and zero.
Referenced by getSize(), opAbs(), opAdd(), opCeil(), opDiv(), opEqual(), opFloat2Float(), opFloor(), opLess(), opLessEqual(), opMult(), opNan(), opNeg(), opNotEqual(), opRound(), opSqrt(), opSub(), and opTrunc().
getInfinityEncoding()
uintb FloatFormat::getInfinityEncoding (bool sgn) const private
Get an encoded infinite value.
Parameters
sgn is set to true for negative infinity, false for positive
Returns
the encoded infinity
References maxexponent, setExponentCode(), setFractionalCode(), and setSign().
Referenced by convertEncoding(), and getEncoding().
getNaNEncoding()
uintb FloatFormat::getNaNEncoding (bool sgn) const private
Get an encoded NaN value.
Parameters
sgn is set to true for negative NaN, false for positive
Returns
the encoded NaN
References maxexponent, setExponentCode(), setFractionalCode(), and setSign().
Referenced by getEncoding().
getZeroEncoding()
uintb FloatFormat::getZeroEncoding (bool sgn) const private
Get an encoded zero value.
Parameters
sgn is set to true for negative zero, false for positive
Returns
the encoded zero
References setExponentCode(), setFractionalCode(), and setSign().
Referenced by convertEncoding(), and getEncoding().
opAbs()
uintb FloatFormat::opAbs (uintb a) const
Absolute value (abs)
Parameters
a is an encoded floating-point value
Returns
abs(a)
References getEncoding(), and getHostFloat().
Referenced by OpBehaviorFloatAbs::evaluateUnary(), and getSize().
opAdd()
uintb FloatFormat::opAdd (uintb a, uintb b) const
Addition (+)
Parameters
a is the first floating-point value
b is the second floating-point value
Returns
a + b
References getEncoding(), and getHostFloat().
Referenced by OpBehaviorFloatAdd::evaluateBinary(), and getSize().
opCeil()
uintb FloatFormat::opCeil (uintb a) const
Ceiling (ceil)
Parameters
a is an encoded floating-point value
Returns
ceil(a)
References getEncoding(), and getHostFloat().
Referenced by OpBehaviorFloatCeil::evaluateUnary(), and getSize().
opDiv()
uintb FloatFormat::opDiv (uintb a, uintb b) const
Division (/)
Parameters
a is the first floating-point value
b is the second floating-point value
Returns
a / b
References getEncoding(), and getHostFloat().
Referenced by OpBehaviorFloatDiv::evaluateBinary(), and getSize().
opEqual()
uintb FloatFormat::opEqual (uintb a, uintb b) const
Equality comparison (==)
Parameters
a is the first floating-point value
b is the second floating-point value
Returns
true if (a == b)
References getHostFloat().
Referenced by OpBehaviorFloatEqual::evaluateBinary(), and getSize().
opFloat2Float()
uintb FloatFormat::opFloat2Float (uintb a, const FloatFormat & outformat) const
Convert between floating-point precisions.
Parameters
a is an encoded floating-point value
outformat is the desired output FloatFormat
Returns
a converted to the output FloatFormat
References getEncoding(), and getHostFloat().
Referenced by OpBehaviorFloatFloat2Float::evaluateUnary(), and getSize().
opFloor()
uintb FloatFormat::opFloor (uintb a) const
Floor (floor)
Parameters
a is an encoded floating-point value
Returns
floor(a)
References getEncoding(), and getHostFloat().
Referenced by OpBehaviorFloatFloor::evaluateUnary(), and getSize().
opInt2Float()
uintb FloatFormat::opInt2Float (uintb a, int4 sizein) const
Convert integer to floating-point.
Parameters
a is a signed integer value
sizein is the number of bytes in the integer encoding
Returns
a converted to an encoded floating-point value
References getEncoding(), and sign_extend().
Referenced by OpBehaviorFloatInt2Float::evaluateUnary(), and getSize().
opLess()
uintb FloatFormat::opLess (uintb a, uintb b) const
Less-than comparison (<)
Parameters
a is the first floating-point value
b is the second floating-point value
Returns
true if (a < b)
References getHostFloat().
Referenced by OpBehaviorFloatLess::evaluateBinary(), and getSize().
opLessEqual()
uintb FloatFormat::opLessEqual (uintb a, uintb b) const
Less-than-or-equal comparison (<=)
Parameters
a is the first floating-point value
b is the second floating-point value
Returns
true if (a <= b)
References getHostFloat().
Referenced by OpBehaviorFloatLessEqual::evaluateBinary(), and getSize().
opMult()
uintb FloatFormat::opMult (uintb a, uintb b) const
Multiplication (*)
Parameters
a is the first floating-point value
b is the second floating-point value
Returns
a * b
References getEncoding(), and getHostFloat().
Referenced by OpBehaviorFloatMult::evaluateBinary(), and getSize().
opNan()
uintb FloatFormat::opNan (uintb a) const
Test if Not-a-Number (NaN)
Parameters
a is an encoded floating-point value
Returns
true if a is Not-a-Number
References getHostFloat(), and nan.
Referenced by OpBehaviorFloatNan::evaluateUnary(), and getSize().
opNeg()
uintb FloatFormat::opNeg (uintb a) const
Unary negate.
Parameters
a is an encoded floating-point value
Returns
-a
References getEncoding(), and getHostFloat().
Referenced by OpBehaviorFloatNeg::evaluateUnary(), and getSize().
opNotEqual()
uintb FloatFormat::opNotEqual (uintb a, uintb b) const
Inequality comparison (!=)
Parameters
a is the first floating-point value
b is the second floating-point value
Returns
true if (a != b)
References getHostFloat().
Referenced by OpBehaviorFloatNotEqual::evaluateBinary(), and getSize().
opRound()
uintb FloatFormat::opRound (uintb a) const
Round.
Parameters
a is an encoded floating-point value
Returns
round(a)
References getEncoding(), and getHostFloat().
Referenced by OpBehaviorFloatRound::evaluateUnary(), and getSize().
opSqrt()
uintb FloatFormat::opSqrt (uintb a) const
Square root (sqrt)
Parameters
a is an encoded floating-point value
Returns
sqrt(a)
References getEncoding(), and getHostFloat().
Referenced by OpBehaviorFloatSqrt::evaluateUnary(), and getSize().
opSub()
uintb FloatFormat::opSub (uintb a, uintb b) const
Subtraction (-)
Parameters
a is the first floating-point value
b is the second floating-point value
Returns
a - b
References getEncoding(), and getHostFloat().
Referenced by OpBehaviorFloatSub::evaluateBinary(), and getSize().
opTrunc()
uintb FloatFormat::opTrunc (uintb a, int4 sizeout) const
Convert floating-point to integer.
Parameters
a is an encoded floating-point value
sizeout is the desired encoding size of the output
Returns
an integer encoding of a
References calc_mask(), and getHostFloat().
Referenced by OpBehaviorFloatTrunc::evaluateUnary(), and getSize().
restoreXml()
void FloatFormat::restoreXml (const Element * el)
Restore the format from XML.
Restore object from a <floatformat> XML tag
Parameters
el is the element
References bias, exp_pos, exp_size, frac_pos, frac_size, jbitimplied, maxexponent, signbit_pos, and size.
Referenced by getSize().
saveXml()
void FloatFormat::saveXml (ostream & s) const
Save the format to an XML stream.
Write the format out to a <floatformat> XML tag.
Parameters
s is the output stream
References bias, exp_pos, exp_size, frac_pos, frac_size, jbitimplied, signbit_pos, and size.
Referenced by getSize().
setExponentCode()
uintb FloatFormat::setExponentCode (uintb x, uintb code) const private
Set the exponent of an encoded value.
Parameters
x is an encoded value (with exponent set to zero)
code is the exponent to set
Returns
the encoded value with the new exponent
References exp_pos.
Referenced by convertEncoding(), getEncoding(), getInfinityEncoding(), getNaNEncoding(), and getZeroEncoding().
setFractionalCode()
uintb FloatFormat::setFractionalCode (uintb x, uintb code) const private
Set the fractional part of an encoded value.
Parameters
x is an encoded value (with fraction part set to zero)
code is the new fractional value to set
Returns
the encoded value with the fractional filled in
References frac_pos, and frac_size.
Referenced by convertEncoding(), getEncoding(), getInfinityEncoding(), getNaNEncoding(), and getZeroEncoding().
setSign()
uintb FloatFormat::setSign (uintb x, bool sign) const private
Set the sign bit of an encoded value.
Parameters
x is an encoded value (with sign set to zero)
sign is the sign bit to set
Returns
the encoded value with the sign bit set
References signbit_pos.
Referenced by convertEncoding(), getEncoding(), getInfinityEncoding(), getNaNEncoding(), and getZeroEncoding().
The documentation for this class was generated from the following files:
float.hh
float.cc